In [1]:
import numpy as np
import keras.backend as k
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from keras.layers import Dense, Dropout
from keras.models import Sequential

Using TensorFlow backend.


In [3]:
data = np.loadtxt('diabeties_new.csv', delimiter=',')

In [8]:
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [11]:
features = data[:,0:8]
target = data[:,8:]

In [12]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [13]:
target

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [14]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.25)

In [15]:
model = Sequential()
model.add(Dense(15, input_dim=8, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

In [16]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
model.fit(x_train, y_train, validation_split=0.2, epochs=1000,verbose=2)

Train on 460 samples, validate on 116 samples
Epoch 1/1000
 - 0s - loss: 0.5810 - accuracy: 0.7043 - val_loss: 0.6569 - val_accuracy: 0.5776
Epoch 2/1000
 - 0s - loss: 0.5650 - accuracy: 0.7022 - val_loss: 0.6671 - val_accuracy: 0.6121
Epoch 3/1000
 - 0s - loss: 0.5608 - accuracy: 0.7239 - val_loss: 0.6828 - val_accuracy: 0.6034
Epoch 4/1000
 - 0s - loss: 0.5575 - accuracy: 0.7239 - val_loss: 0.6633 - val_accuracy: 0.6034
Epoch 5/1000
 - 0s - loss: 0.5579 - accuracy: 0.7261 - val_loss: 0.6728 - val_accuracy: 0.5862
Epoch 6/1000
 - 0s - loss: 0.5580 - accuracy: 0.7152 - val_loss: 0.6699 - val_accuracy: 0.5690
Epoch 7/1000
 - 0s - loss: 0.5796 - accuracy: 0.7022 - val_loss: 0.6781 - val_accuracy: 0.5948
Epoch 8/1000
 - 0s - loss: 0.5512 - accuracy: 0.7304 - val_loss: 0.6716 - val_accuracy: 0.6034
Epoch 9/1000
 - 0s - loss: 0.5465 - accuracy: 0.7152 - val_loss: 0.6722 - val_accuracy: 0.6121
Epoch 10/1000
 - 0s - loss: 0.5540 - accuracy: 0.7065 - val_loss: 0.6806 - val_accuracy: 0.6034
Epo

Epoch 86/1000
 - 0s - loss: 0.5171 - accuracy: 0.7609 - val_loss: 0.6780 - val_accuracy: 0.6379
Epoch 87/1000
 - 0s - loss: 0.5306 - accuracy: 0.7457 - val_loss: 0.6692 - val_accuracy: 0.6121
Epoch 88/1000
 - 0s - loss: 0.5216 - accuracy: 0.7543 - val_loss: 0.6921 - val_accuracy: 0.6293
Epoch 89/1000
 - 0s - loss: 0.5113 - accuracy: 0.7522 - val_loss: 0.6705 - val_accuracy: 0.6552
Epoch 90/1000
 - 0s - loss: 0.5072 - accuracy: 0.7630 - val_loss: 0.6861 - val_accuracy: 0.6552
Epoch 91/1000
 - 0s - loss: 0.5320 - accuracy: 0.7217 - val_loss: 0.6712 - val_accuracy: 0.6552
Epoch 92/1000
 - 0s - loss: 0.5138 - accuracy: 0.7522 - val_loss: 0.6679 - val_accuracy: 0.6293
Epoch 93/1000
 - 0s - loss: 0.5344 - accuracy: 0.7217 - val_loss: 0.6883 - val_accuracy: 0.6293
Epoch 94/1000
 - 0s - loss: 0.5021 - accuracy: 0.7609 - val_loss: 0.6744 - val_accuracy: 0.6466
Epoch 95/1000
 - 0s - loss: 0.5308 - accuracy: 0.7413 - val_loss: 0.6653 - val_accuracy: 0.6466
Epoch 96/1000
 - 0s - loss: 0.5252 - acc

Epoch 171/1000
 - 0s - loss: 0.5018 - accuracy: 0.7587 - val_loss: 0.6778 - val_accuracy: 0.6466
Epoch 172/1000
 - 0s - loss: 0.4956 - accuracy: 0.7717 - val_loss: 0.6947 - val_accuracy: 0.6724
Epoch 173/1000
 - 0s - loss: 0.5012 - accuracy: 0.7457 - val_loss: 0.7139 - val_accuracy: 0.6379
Epoch 174/1000
 - 0s - loss: 0.5067 - accuracy: 0.7500 - val_loss: 0.6869 - val_accuracy: 0.6552
Epoch 175/1000
 - 0s - loss: 0.5246 - accuracy: 0.7457 - val_loss: 0.6953 - val_accuracy: 0.6466
Epoch 176/1000
 - 0s - loss: 0.5229 - accuracy: 0.7457 - val_loss: 0.6732 - val_accuracy: 0.6810
Epoch 177/1000
 - 0s - loss: 0.5073 - accuracy: 0.7413 - val_loss: 0.6902 - val_accuracy: 0.6638
Epoch 178/1000
 - 0s - loss: 0.5012 - accuracy: 0.7543 - val_loss: 0.6968 - val_accuracy: 0.6379
Epoch 179/1000
 - 0s - loss: 0.4956 - accuracy: 0.7630 - val_loss: 0.7036 - val_accuracy: 0.6379
Epoch 180/1000
 - 0s - loss: 0.5170 - accuracy: 0.7391 - val_loss: 0.6952 - val_accuracy: 0.6293
Epoch 181/1000
 - 0s - loss: 0

Epoch 256/1000
 - 0s - loss: 0.5014 - accuracy: 0.7413 - val_loss: 0.7349 - val_accuracy: 0.6293
Epoch 257/1000
 - 0s - loss: 0.4598 - accuracy: 0.7870 - val_loss: 0.7147 - val_accuracy: 0.6724
Epoch 258/1000
 - 0s - loss: 0.4769 - accuracy: 0.7587 - val_loss: 0.7429 - val_accuracy: 0.6466
Epoch 259/1000
 - 0s - loss: 0.4912 - accuracy: 0.7630 - val_loss: 0.7112 - val_accuracy: 0.6810
Epoch 260/1000
 - 0s - loss: 0.4879 - accuracy: 0.7630 - val_loss: 0.7257 - val_accuracy: 0.6121
Epoch 261/1000
 - 0s - loss: 0.4763 - accuracy: 0.7717 - val_loss: 0.7239 - val_accuracy: 0.6724
Epoch 262/1000
 - 0s - loss: 0.4673 - accuracy: 0.7739 - val_loss: 0.7376 - val_accuracy: 0.6379
Epoch 263/1000
 - 0s - loss: 0.4675 - accuracy: 0.7739 - val_loss: 0.7214 - val_accuracy: 0.6207
Epoch 264/1000
 - 0s - loss: 0.4736 - accuracy: 0.7674 - val_loss: 0.7321 - val_accuracy: 0.6293
Epoch 265/1000
 - 0s - loss: 0.4474 - accuracy: 0.7957 - val_loss: 0.7165 - val_accuracy: 0.7155
Epoch 266/1000
 - 0s - loss: 0

Epoch 341/1000
 - 0s - loss: 0.4768 - accuracy: 0.7652 - val_loss: 0.7398 - val_accuracy: 0.6638
Epoch 342/1000
 - 0s - loss: 0.4693 - accuracy: 0.7696 - val_loss: 0.7342 - val_accuracy: 0.6638
Epoch 343/1000
 - 0s - loss: 0.4593 - accuracy: 0.7717 - val_loss: 0.7557 - val_accuracy: 0.6207
Epoch 344/1000
 - 0s - loss: 0.4638 - accuracy: 0.7652 - val_loss: 0.7391 - val_accuracy: 0.6724
Epoch 345/1000
 - 0s - loss: 0.4729 - accuracy: 0.7652 - val_loss: 0.7656 - val_accuracy: 0.6466
Epoch 346/1000
 - 0s - loss: 0.4465 - accuracy: 0.7717 - val_loss: 0.7444 - val_accuracy: 0.6638
Epoch 347/1000
 - 0s - loss: 0.4588 - accuracy: 0.7761 - val_loss: 0.7535 - val_accuracy: 0.6638
Epoch 348/1000
 - 0s - loss: 0.4576 - accuracy: 0.7870 - val_loss: 0.7537 - val_accuracy: 0.6724
Epoch 349/1000
 - 0s - loss: 0.4508 - accuracy: 0.7804 - val_loss: 0.7493 - val_accuracy: 0.6724
Epoch 350/1000
 - 0s - loss: 0.4556 - accuracy: 0.7783 - val_loss: 0.7748 - val_accuracy: 0.6379
Epoch 351/1000
 - 0s - loss: 0

Epoch 426/1000
 - 0s - loss: 0.4462 - accuracy: 0.8022 - val_loss: 0.7695 - val_accuracy: 0.6638
Epoch 427/1000
 - 0s - loss: 0.4432 - accuracy: 0.7870 - val_loss: 0.7757 - val_accuracy: 0.6552
Epoch 428/1000
 - 0s - loss: 0.4571 - accuracy: 0.7674 - val_loss: 0.7633 - val_accuracy: 0.6638
Epoch 429/1000
 - 0s - loss: 0.4412 - accuracy: 0.8022 - val_loss: 0.7786 - val_accuracy: 0.6724
Epoch 430/1000
 - 0s - loss: 0.4352 - accuracy: 0.7935 - val_loss: 0.7593 - val_accuracy: 0.6724
Epoch 431/1000
 - 0s - loss: 0.4375 - accuracy: 0.7848 - val_loss: 0.7962 - val_accuracy: 0.6638
Epoch 432/1000
 - 0s - loss: 0.4375 - accuracy: 0.7935 - val_loss: 0.7671 - val_accuracy: 0.6638
Epoch 433/1000
 - 0s - loss: 0.4343 - accuracy: 0.7848 - val_loss: 0.7936 - val_accuracy: 0.6724
Epoch 434/1000
 - 0s - loss: 0.4423 - accuracy: 0.7717 - val_loss: 0.7808 - val_accuracy: 0.6724
Epoch 435/1000
 - 0s - loss: 0.4595 - accuracy: 0.7804 - val_loss: 0.7590 - val_accuracy: 0.6466
Epoch 436/1000
 - 0s - loss: 0

Epoch 511/1000
 - 0s - loss: 0.4264 - accuracy: 0.8000 - val_loss: 0.7696 - val_accuracy: 0.6897
Epoch 512/1000
 - 0s - loss: 0.4351 - accuracy: 0.7978 - val_loss: 0.7836 - val_accuracy: 0.6810
Epoch 513/1000
 - 0s - loss: 0.4390 - accuracy: 0.7957 - val_loss: 0.7925 - val_accuracy: 0.6638
Epoch 514/1000
 - 0s - loss: 0.4226 - accuracy: 0.7935 - val_loss: 0.7848 - val_accuracy: 0.6983
Epoch 515/1000
 - 0s - loss: 0.4585 - accuracy: 0.7826 - val_loss: 0.7644 - val_accuracy: 0.6724
Epoch 516/1000
 - 0s - loss: 0.4416 - accuracy: 0.7913 - val_loss: 0.7814 - val_accuracy: 0.6552
Epoch 517/1000
 - 0s - loss: 0.4271 - accuracy: 0.7935 - val_loss: 0.8007 - val_accuracy: 0.6897
Epoch 518/1000
 - 0s - loss: 0.4294 - accuracy: 0.7870 - val_loss: 0.8084 - val_accuracy: 0.6810
Epoch 519/1000
 - 0s - loss: 0.4331 - accuracy: 0.7826 - val_loss: 0.7848 - val_accuracy: 0.6810
Epoch 520/1000
 - 0s - loss: 0.4444 - accuracy: 0.7826 - val_loss: 0.7962 - val_accuracy: 0.6638
Epoch 521/1000
 - 0s - loss: 0

Epoch 596/1000
 - 0s - loss: 0.4271 - accuracy: 0.8000 - val_loss: 0.8112 - val_accuracy: 0.6810
Epoch 597/1000
 - 0s - loss: 0.4238 - accuracy: 0.7891 - val_loss: 0.8477 - val_accuracy: 0.6897
Epoch 598/1000
 - 0s - loss: 0.4344 - accuracy: 0.7848 - val_loss: 0.8480 - val_accuracy: 0.6897
Epoch 599/1000
 - 0s - loss: 0.4059 - accuracy: 0.8043 - val_loss: 0.8114 - val_accuracy: 0.6983
Epoch 600/1000
 - 0s - loss: 0.4338 - accuracy: 0.7783 - val_loss: 0.8262 - val_accuracy: 0.6897
Epoch 601/1000
 - 0s - loss: 0.4310 - accuracy: 0.7804 - val_loss: 0.8307 - val_accuracy: 0.6810
Epoch 602/1000
 - 0s - loss: 0.4160 - accuracy: 0.7848 - val_loss: 0.8734 - val_accuracy: 0.6724
Epoch 603/1000
 - 0s - loss: 0.4196 - accuracy: 0.8065 - val_loss: 0.8327 - val_accuracy: 0.7069
Epoch 604/1000
 - 0s - loss: 0.4256 - accuracy: 0.7870 - val_loss: 0.8604 - val_accuracy: 0.6897
Epoch 605/1000
 - 0s - loss: 0.4180 - accuracy: 0.8043 - val_loss: 0.7959 - val_accuracy: 0.6983
Epoch 606/1000
 - 0s - loss: 0

Epoch 681/1000
 - 0s - loss: 0.4071 - accuracy: 0.7978 - val_loss: 0.8900 - val_accuracy: 0.7069
Epoch 682/1000
 - 0s - loss: 0.4370 - accuracy: 0.7848 - val_loss: 0.9556 - val_accuracy: 0.6983
Epoch 683/1000
 - 0s - loss: 0.4097 - accuracy: 0.7870 - val_loss: 0.9280 - val_accuracy: 0.6810
Epoch 684/1000
 - 0s - loss: 0.4097 - accuracy: 0.7826 - val_loss: 0.9624 - val_accuracy: 0.7155
Epoch 685/1000
 - 0s - loss: 0.4144 - accuracy: 0.8087 - val_loss: 0.9316 - val_accuracy: 0.7155
Epoch 686/1000
 - 0s - loss: 0.4194 - accuracy: 0.7978 - val_loss: 0.8971 - val_accuracy: 0.6983
Epoch 687/1000
 - 0s - loss: 0.4016 - accuracy: 0.8043 - val_loss: 0.9632 - val_accuracy: 0.7069
Epoch 688/1000
 - 0s - loss: 0.4105 - accuracy: 0.7891 - val_loss: 0.9301 - val_accuracy: 0.6897
Epoch 689/1000
 - 0s - loss: 0.4072 - accuracy: 0.8000 - val_loss: 0.8755 - val_accuracy: 0.6810
Epoch 690/1000
 - 0s - loss: 0.4038 - accuracy: 0.8043 - val_loss: 0.9232 - val_accuracy: 0.6897
Epoch 691/1000
 - 0s - loss: 0

Epoch 766/1000
 - 0s - loss: 0.3966 - accuracy: 0.8130 - val_loss: 1.0171 - val_accuracy: 0.6810
Epoch 767/1000
 - 0s - loss: 0.4233 - accuracy: 0.7848 - val_loss: 0.9786 - val_accuracy: 0.6810
Epoch 768/1000
 - 0s - loss: 0.3864 - accuracy: 0.8065 - val_loss: 1.0688 - val_accuracy: 0.6983
Epoch 769/1000
 - 0s - loss: 0.4064 - accuracy: 0.7913 - val_loss: 0.9894 - val_accuracy: 0.6810
Epoch 770/1000
 - 0s - loss: 0.4021 - accuracy: 0.8043 - val_loss: 1.0664 - val_accuracy: 0.6724
Epoch 771/1000
 - 0s - loss: 0.4021 - accuracy: 0.8087 - val_loss: 1.0664 - val_accuracy: 0.6897
Epoch 772/1000
 - 0s - loss: 0.3874 - accuracy: 0.7935 - val_loss: 1.0339 - val_accuracy: 0.7155
Epoch 773/1000
 - 0s - loss: 0.3945 - accuracy: 0.8130 - val_loss: 1.0791 - val_accuracy: 0.6983
Epoch 774/1000
 - 0s - loss: 0.3890 - accuracy: 0.8022 - val_loss: 1.0718 - val_accuracy: 0.6983
Epoch 775/1000
 - 0s - loss: 0.3896 - accuracy: 0.8065 - val_loss: 1.0423 - val_accuracy: 0.6897
Epoch 776/1000
 - 0s - loss: 0

Epoch 851/1000
 - 0s - loss: 0.3865 - accuracy: 0.8000 - val_loss: 0.9836 - val_accuracy: 0.6983
Epoch 852/1000
 - 0s - loss: 0.4124 - accuracy: 0.7957 - val_loss: 0.8907 - val_accuracy: 0.6810
Epoch 853/1000
 - 0s - loss: 0.4303 - accuracy: 0.7783 - val_loss: 0.9945 - val_accuracy: 0.6897
Epoch 854/1000
 - 0s - loss: 0.4192 - accuracy: 0.7783 - val_loss: 0.9435 - val_accuracy: 0.6638
Epoch 855/1000
 - 0s - loss: 0.4063 - accuracy: 0.8043 - val_loss: 0.9561 - val_accuracy: 0.6724
Epoch 856/1000
 - 0s - loss: 0.3996 - accuracy: 0.7935 - val_loss: 0.8978 - val_accuracy: 0.7069
Epoch 857/1000
 - 0s - loss: 0.4189 - accuracy: 0.8065 - val_loss: 0.9256 - val_accuracy: 0.6983
Epoch 858/1000
 - 0s - loss: 0.4226 - accuracy: 0.7913 - val_loss: 0.9266 - val_accuracy: 0.6983
Epoch 859/1000
 - 0s - loss: 0.4062 - accuracy: 0.7870 - val_loss: 1.0325 - val_accuracy: 0.6897
Epoch 860/1000
 - 0s - loss: 0.3999 - accuracy: 0.7913 - val_loss: 0.9674 - val_accuracy: 0.6897
Epoch 861/1000
 - 0s - loss: 0

Epoch 936/1000
 - 0s - loss: 0.3806 - accuracy: 0.8043 - val_loss: 1.1714 - val_accuracy: 0.6897
Epoch 937/1000
 - 0s - loss: 0.3816 - accuracy: 0.8043 - val_loss: 1.2202 - val_accuracy: 0.6724
Epoch 938/1000
 - 0s - loss: 0.3798 - accuracy: 0.8022 - val_loss: 1.2147 - val_accuracy: 0.6983
Epoch 939/1000
 - 0s - loss: 0.3793 - accuracy: 0.8043 - val_loss: 1.1855 - val_accuracy: 0.6983
Epoch 940/1000
 - 0s - loss: 0.3729 - accuracy: 0.8109 - val_loss: 1.1572 - val_accuracy: 0.6897
Epoch 941/1000
 - 0s - loss: 0.3738 - accuracy: 0.8087 - val_loss: 1.2312 - val_accuracy: 0.7069
Epoch 942/1000
 - 0s - loss: 0.3960 - accuracy: 0.8043 - val_loss: 1.1138 - val_accuracy: 0.6810
Epoch 943/1000
 - 0s - loss: 0.3932 - accuracy: 0.7913 - val_loss: 1.2003 - val_accuracy: 0.6810
Epoch 944/1000
 - 0s - loss: 0.4150 - accuracy: 0.7891 - val_loss: 1.1482 - val_accuracy: 0.6983
Epoch 945/1000
 - 0s - loss: 0.3948 - accuracy: 0.7913 - val_loss: 1.1582 - val_accuracy: 0.6810
Epoch 946/1000
 - 0s - loss: 0

In [19]:
preds = model.predict(x_test, verbose=0)

In [20]:
preds

array([[7.59969640e-04],
       [7.33053410e-11],
       [4.32854235e-01],
       [8.16952015e-05],
       [2.80766457e-01],
       [3.46905708e-01],
       [4.27540541e-02],
       [1.79704381e-04],
       [4.28017205e-18],
       [1.35684371e-01],
       [8.51109266e-01],
       [6.28826499e-01],
       [1.01600371e-01],
       [4.03934866e-02],
       [2.29380722e-03],
       [1.61379084e-01],
       [4.49093908e-01],
       [4.11130190e-02],
       [2.22565569e-02],
       [8.52262974e-03],
       [2.16192522e-04],
       [1.46568611e-01],
       [7.63634518e-02],
       [9.38665330e-01],
       [7.20269504e-18],
       [2.82598674e-01],
       [9.17235255e-01],
       [6.97454572e-01],
       [1.69272628e-02],
       [6.39297187e-01],
       [4.89493698e-01],
       [5.36769748e-01],
       [3.46905708e-01],
       [9.53656077e-01],
       [6.25342607e-01],
       [9.79008198e-01],
       [1.00077376e-01],
       [8.62489641e-01],
       [2.46069595e-01],
       [4.91486311e-01],


In [23]:
pred_cls = model.predict_classes(x_test, verbose=0)

In [21]:
model.evaluate(x_test, y_test)

192/192 [==============================] - 0s 49us/step


[0.9991501222054163, 0.7447916865348816]

In [24]:
pred_cls

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [26]:
cm = confusion_matrix(pred_cls, y_test)
cm

array([[108,  31],
       [ 18,  35]], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
score = accuracy_score(pred_cls, y_test)
score

0.7447916666666666

In [ ]:
plt.figure(figsize=(12,6))
sns.heatmap(cm, annot=True)
plt.xlabel('predicted')
plt.ylabel('trut')