In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [4]:
action_space = env.action_space.n
state_space = env.observation_space.n
q_table = np.zeros((state_space, action_space))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [9]:
reward_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode):
        threshold = random.uniform(0,1)
        if threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        q_table[state, action] =  q_table[state, action]*(1-learning_rate) + \
                                    learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward
        if done == True:
            break
    exploration_rate = min_exploration_rate + \
                        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    reward_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count = 1000
print('***** average reward per 1000 episodes *****\n')
for r in rewards_per_thousand_episodes :
    a = sum(r/1000)
    print('{} : {}'.format(count, a))
    count += 1000
    
print('***** q_table *****\n')
print(q_table)

***** average reward per 1000 episodes *****

1000 : 0.05000000000000004
2000 : 0.19300000000000014
3000 : 0.4040000000000003
4000 : 0.5570000000000004
5000 : 0.5960000000000004
6000 : 0.6660000000000005
7000 : 0.6630000000000005
8000 : 0.6920000000000005
9000 : 0.6620000000000005
10000 : 0.6940000000000005
***** q_table *****

[[0.54675815 0.52215134 0.52244177 0.51819315]
 [0.30608414 0.38359617 0.20170262 0.51615321]
 [0.40435665 0.40374435 0.40734035 0.47808411]
 [0.32424191 0.30701174 0.28191751 0.47040235]
 [0.5664303  0.40290315 0.29387794 0.42468524]
 [0.         0.         0.         0.        ]
 [0.17940385 0.16527691 0.40596947 0.14494084]
 [0.         0.         0.         0.        ]
 [0.38364097 0.53594128 0.46251837 0.60713004]
 [0.47889058 0.6394758  0.49536033 0.46592834]
 [0.52312508 0.30281572 0.22867991 0.31813709]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45493471 0.55518558 0.77861385 0.54928058]
 [0.72321517

In [8]:
print(q_table)

[[0.53950126 0.46599422 0.45210608 0.46726959]
 [0.34843393 0.3219478  0.38934911 0.48793137]
 [0.38178153 0.38383072 0.38320749 0.45190005]
 [0.33363217 0.24512808 0.36708641 0.43509929]
 [0.56074553 0.37441685 0.34682401 0.37745017]
 [0.         0.         0.         0.        ]
 [0.2677588  0.11234018 0.13318736 0.116713  ]
 [0.         0.         0.         0.        ]
 [0.42783586 0.45884666 0.36004852 0.58000183]
 [0.42341603 0.62990431 0.28537436 0.39688094]
 [0.57016169 0.36477794 0.32709719 0.3591872 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54731901 0.52345891 0.71918972 0.3624874 ]
 [0.71886881 0.87652898 0.71414464 0.69238859]
 [0.         0.         0.         0.        ]]


In [14]:
for episode in range(4):
    state = env.reset()
    done = False
    print('***** episode  ',episode+1,' *****')
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                print('***** you reached goal *****')
                time.sleep(1)
            else:
                print('***** you entered hole *****')
                time.sleep(1)
                
            clear_output(wait = True)
            
            break
        state = new_state
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
***** you entered hole *****


hello
